# Generated by Django 2.1.4 on 2019-01-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bought',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
