# Generated by Django 2.1.4 on 2019-01-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0007_auto_20190105_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('seller', models.CharField(max_length=50)),
                ('seller_number', models.CharField(max_length=50)),
                ('seller_address', models.TextField(blank=True)),
                ('buyer', models.CharField(max_length=50)),
                ('buyer_number', models.CharField(max_length=50)),
                ('buyer_address', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Product')),
            ],
        ),
    ]
