# Generated by Django 2.1.4 on 2019-01-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='buyer_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sold',
            name='delivered',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sold',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sold',
            name='seller_address',
            field=models.TextField(),
        ),
    ]
