# Generated by Django 2.1.4 on 2019-01-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190121_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment',
            field=models.CharField(blank=True, default='No Work Mentioned', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(blank=True, default='No Hobbies Mentioned', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default='No Address Mentioned', null=True),
        ),
    ]
