# Generated by Django 2.1.4 on 2019-01-26 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190126_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='No Contact Number Mentioned', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits only', regex='^\\d{10}$')]),
        ),
    ]
