# Generated by Django 2.1.4 on 2019-01-28 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='from_place',
            field=models.CharField(blank=True, default='Not Mentioned', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lives_in',
            field=models.CharField(blank=True, default='Not Mentioned', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.TextField(blank=True, default='Not Mentioned', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='Not Mentioned', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment',
            field=models.CharField(blank=True, default='Not Mentioned', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(blank=True, default='Not Mentioned', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='Not Mentioned', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits only', regex='^\\d{10}$')]),
        ),
    ]
